package rules

import br.com.ifs.TCC.SintomasClassificacao

rule "Criança articulação quente"
	when 
                offerObject: SintomasClassificacao(Sintomas=="articulacao_quente" && Grupo=="criancas")
	then
		offerObject.setClassificacao("AMARELA");
	end

rule "Criança Choro prolongado e initerrupto"
	when 
                offerObject: SintomasClassificacao(Sintomas=="choro_prolongado_e_initerrupto" && Grupo=="criancas")
	then
		offerObject.setClassificacao("AMARELA");
	end

rule "Criança distúrbio de coagulaçao"
	when 
                offerObject: SintomasClassificacao(Sintomas=="disturbio_de_coagulacao" && Grupo=="criancas")
	then
		offerObject.setClassificacao("AMARELA");
	end

rule "Criança dor ao movimento articular"
	when 
                offerObject: SintomasClassificacao(Sintomas=="dor_ao_movimento_articular" && Grupo=="criancas")
	then
		offerObject.setClassificacao("AMARELA");
	end

rule "Criança dor pleurítica"
	when 
                offerObject: SintomasClassificacao(Sintomas=="dor_pleuritica" && Grupo=="criancas")
	then
		offerObject.setClassificacao("AMARELA");
	end

rule "Criança fezes pretas ou em groselha"
	when 
                offerObject: SintomasClassificacao(Sintomas=="fezes_pretas_ou_em_groselha" && Grupo=="criancas")
	then
		offerObject.setClassificacao("AMARELA");
	end

rule "Criança história aguda de vomito de sangue"
	when 
                offerObject: SintomasClassificacao(Sintomas=="historia_aguda_de_vomito_de_sangue" && Grupo=="criancas")
	then
		offerObject.setClassificacao("AMARELA");
	end

rule "Criança história de hemoptise"
	when 
                offerObject: SintomasClassificacao(Sintomas=="historia_de-hemoptise" && Grupo=="criancas")
	then
		offerObject.setClassificacao("AMARELA");
	end

rule "Criança História de inconsciência"
	when 
                offerObject: SintomasClassificacao(Sintomas=="historia_de_inconsciencia" && Grupo=="criancas")
	then
		offerObject.setClassificacao("AMARELA");
	end

rule "Criança História discordante"
	when 
                offerObject: SintomasClassificacao(Sintomas=="historia_discordante" && Grupo=="criancas")
	then
		offerObject.setClassificacao("AMARELA");
	end

rule "Criança Sinais de desidratação"
	when 
                offerObject: SintomasClassificacao(Sintomas=="sinais_de_desidratacao" && Grupo=="criancas")
	then
		offerObject.setClassificacao("AMARELA");
	end

rule "Criança Sem urinar"
	when 
                offerObject: SintomasClassificacao(Sintomas=="sem_urinar" && Grupo=="criancas")
	then
		offerObject.setClassificacao("AMARELA");
	end

rule "Criança sat O2 baixa"
	when 
                offerObject: SintomasClassificacao(Sintomas=="sat_o2_baixa" && Grupo=="criancas")
	then
		offerObject.setClassificacao("AMARELA");
	end

rule "Criança PFE baixo"
	when 
                offerObject: SintomasClassificacao(Sintomas=="pfe_baixo" && Grupo=="criancas")
	then
		offerObject.setClassificacao("AMARELA");
	end

rule "Criança Não se alimenta"
	when 
                offerObject: SintomasClassificacao(Sintomas=="nao_se_alimenta" && Grupo=="criancas")
	then
		offerObject.setClassificacao("AMARELA");
	end

rule "Criança vomitos persistentes"
	when 
                offerObject: SintomasClassificacao(Sintomas=="vomitos_persistentes" && Grupo=="criancas")
	then
		offerObject.setClassificacao("AMARELA");
	end

rule "Criança Não entretível"
	when 
                offerObject: SintomasClassificacao(Sintomas=="nao_entretivel" && Grupo=="criancas")
	then
		offerObject.setClassificacao("AMARELA");
	end

rule "Criança massa abdominal visível"
	when 
                offerObject: SintomasClassificacao(Sintomas=="massa_abdominal_visível" && Grupo=="criancas")
	then
		offerObject.setClassificacao("AMARELA");
	end

rule "Criança inconsolável pelos pais"
	when 
                offerObject: SintomasClassificacao(Sintomas=="inconsolavel_pelos_pais" && Grupo=="criancas")
	then
		offerObject.setClassificacao("AMARELA");
	end

rule "Criança Incapaz de se alimentar"
	when 
                offerObject: SintomasClassificacao(Sintomas=="incapaz_de_ se_alimentar" && Grupo=="criancas")
	then
		offerObject.setClassificacao("AMARELA");
	end










