package rules

import br.com.ifs.TCC.SintomasClassificacao

rule "Criança Baba-se"
	when 
                offerObject: SintomasClassificacao(Sintomas=="baba_se" && Grupo=="criancas")
	then
		offerObject.setClassificacao("VERMELHA");
	end

rule "Criança hipoglicemia"
	when 
		offerObject: SintomasClassificacao(Grupo=="criancas" && Sintomas=="hipoglicemia")
	then
		offerObject.setClassificacao("VERMELHA");
	end

rule "Criança nao reativa"
	when 
		offerObject: SintomasClassificacao(Grupo=="criancas" && Sintomas=="nao_reativa")
	then
		offerObject.setClassificacao("VERMELHA");
	end

rule "Criança Obstrução das vias aereas"
	when 
		offerObject: SintomasClassificacao(Grupo=="criancas" && Sintomas=="obstrucao_das_vias_aereas")
	then
		offerObject.setClassificacao("VERMELHA");
	end

rule "Criança Respiração Inadequada"
	when 
		offerObject: SintomasClassificacao(Grupo=="criancas" && Sintomas=="respiracao_inadequada")
	then
		offerObject.setClassificacao("VERMELHA");
	end

rule "Criança choque"
	when 
		offerObject: SintomasClassificacao(Grupo=="criancas" && Sintomas=="choque")
	then
		offerObject.setClassificacao("VERMELHA");
	end

rule "Criança Convulsionando"
	when 
		offerObject: SintomasClassificacao(Grupo=="criancas" && Sintomas=="convulsionando")
	then
		offerObject.setClassificacao("VERMELHA");
	end

rule "Criança Hipoglicemia"
	when 
		offerObject: SintomasClassificacao(Grupo=="criancas" && Sintomas=="hipoglicemia")
	then
		offerObject.setClassificacao("VERMELHA");
	end

rule "Criança Não Reativa"
	when 
		offerObject: SintomasClassificacao(Grupo=="criancas" && Sintomas=="nao_reativa")
	then
		offerObject.setClassificacao("VERMELHA");
	end

rule "Criança estridor"
	when 
		offerObject: SintomasClassificacao(Grupo=="criancas" && Sintomas=="estridor")
	then
		offerObject.setClassificacao("VERMELHA");
	end






